apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-data
  namespace: monitoring
data:
  device1.snmprec: |
    .1.3.6.1.2.1.1.1.0|4|Cisco Router Model XYZ
    .1.3.6.1.2.1.1.3.0|67|123456
    .1.3.6.1.2.1.1.5.0|4|CatRouter
  device2.snmprec: |
    .1.3.6.1.2.1.1.1.0|4|Juniper Switch Model ABC
    .1.3.6.1.2.1.1.3.0|67|654321
    .1.3.6.1.2.1.1.5.0|4|SwitchFrontend
  device3.snmprec: |
    .1.3.6.1.2.1.1.1.0|4|Firewall Device Model FW-2025
    .1.3.6.1.2.1.1.3.0|67|345678
    .1.3.6.1.2.1.1.5.0|4|Firewall-01
    .1.3.6.1.4.1.2021.4.5.0|2|4096
    .1.3.6.1.4.1.9.2.1.56.0|2|15         
