apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-config
  namespace: monitoring
data:
  ZBX_SERVER_NAME: "zabbix_k8s"
  ZBX_SERVER_HOST: "zabbix-server.monitoring.svc"
  ZBX_HOSTNAME: "Zabbix server"
  ZBX_PROXY_HOSTNAME: "zabbix-proxy"
  ZBX_AGENT_SERVER_HOST: "0.0.0.0/0"
  ZBX_SERVER_PORT: "10051"
  PHP_TZ: "Europe/Riga"
  ZBX_DEBUGLEVEL: "4"
  ZBX_WEBSERVICEURL: "http://zabbix-webservice:10053/report"
  ZBX_ENABLE_SNMP_TRAPS: "true"
