---
apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: monitoring
type: Opaque
stringData:
  DB_SERVER_HOST: 'zabbix-postgresql'
  DB_SERVER_PORT: '5432'
  POSTGRES_USER: 'zabbix'
  POSTGRES_PASSWORD: 'zabbix'
  POSTGRES_DB: 'zabbix'

